### PR TITLE
Better logging.

### PR DESCRIPTION
**Pull request by JasonLG1979**
Doesn't change console logging behavior. 
Creates a ~/.pithos folder and logs at a WARNING level to 'event.log' by default. 
added new command line args -f and -e.
-f sets the logging level for the log file to INFO and -e sets the logging level for the log file to DEBUG.
Should make debugging and trouble shooting user issues easier.

### CODE REVIEW

**Comment by TingPing** [comment]
Maybe this is valuable on Windows (which we still don't support), but uh, what is wrong with `pithos -v 2> event.log`?

**Comment by JasonLG1979** [comment]
Because this outputs to a log file at a WARNING level all the time. Users don't generally run Pithos from the terminal so this way when something goes wrong they/we would have a record of it.

**Comment by JasonLG1979** [comment]
Like I said it would help with trouble shooting user issues. cat .pithos/event.log is a lot easier then running Pithos over and over again from the terminal to find sporadic/random errors. How many times have you tried to trouble shoot user issues here on github and wished you could get better info from them?

**Comment by TingPing** [comment]
Personally I'd say it has been pretty easy to tell users "rerun with `pithos -v` and pastebin the output.".

**Comment by JasonLG1979** [comment]
> Personally I'd say it has been pretty easy to tell users "rerun with pithos -v and pastebin the output.".

Only helps after the fact. And if the error doesn't happen again you have no idea what happened the 1st time. Like I said this outputs at a WARNING level all the time. Errors and such get logged to file no matter if you run Pithos from the terminal or not.

**Comment by JasonLG1979** [comment]
If you'd like to continue to trouble shoot "This happened, I have no idea why and I have no idea how to get you more info" issues. Then I guess that's your call,lol!!!

**Comment by TingPing** [comment]
Heh, I come from HexChat which is 60k lines of C with absolutely no logging of any kind, debugging Pithos is already a dream compared to this :P

**Comment by JasonLG1979** [comment]
> Heh, I come from HexChat which is 60k lines of C with absolutely no logging of any kind, debugging Pithos is already a dream compared to this :P

For you maybe but not the average user.

**Comment by JasonLG1979** [comment]
I guess I don't understand the resistance. You're acting like I'm from Mars because I'd like to log errors to a log file,lol!!! It's a pretty common practice...

**Comment by TingPing** [comment]
Well I just like things that are added to have very clear and obvious 'value' to me. Features added just because don't lead to a clean codebase. I know that this is a very minor patch and I am not necessarily that against it I just don't think it is useful.

The one and only real problem I can think of it atm is that it will just continually grow the file forever since it doesn't seem to limit the size or even rotate it.

**Comment by JasonLG1979** [comment]
> The only real problem I can think of it atm is that it will just continually grow the file forever since it doesn't seem to limit the size or even rotate it. Oh and it puts it in a terrible location.

It should log very little to nothing by default. And I don't know the proper location. It's user specific so somewhere in their home dir?

**Comment by JasonLG1979** [comment]
Best I can come up with to limit log file size is something like this:
```python
    if os.path.exists(log_file):
        line_offset = []
        offset = 0
        number_of_lines = 0
        with open(log_file, 'rb+') as log:
            for line in log:
                #get the number of lines and each line's offset
                line_offset.append(offset)
                offset += len(line)
                number_of_lines += 1
            if number_of_lines > 250: #250 lines is plenty enough for debugging problems
                delete_before_line = number_of_lines - 250 #the line we want to seek to
                log.seek(line_offset[delete_before_line]) #seek to the line offset of the delete_before_line 
                keeper_lines = log.read() #the last 250 lines
                log.seek(0) #rewind to start of file
                log.write(keeper_lines) #write back the last 250 lines 
                log.truncate()
            log.close()
```
This would keep the last 250 log messages. 250 lines would be a pretty long log but the file size as far as space would be pretty tiny.

**Pull request closed without merging**
