### PR TITLE
song.title should not be a property

### PR DESCRIPTION
**Pull request by JasonLG1979**
If song.title is a decorated property with a getter that means that the 1st thing to access it has to potentially do a blocking network call. It just so happens that the 1st thing to access song.title does so from the main thread. Doing blocking calls from the main thread is ofc bad. This instead moves checking the title to init to make sure that any blocking calls are done from a worker thread.

I never really noticed the UI blocking until recently because I've had issues with my internet connection. So I threw a ```print(threading.get_ident())``` in the title prop and sure enough it was doing blocking I/O in the main thread.

### CODE REVIEW

**Comment by TingPing** [comment]
But now something will get the wrong empty title?

**Comment by JasonLG1979** [comment]
No. title will always either be the value from the explorer url or songName. Nothing will get an empty string because that function is called during class creation in a worker thread before anything else tries to access title.

**Comment by JasonLG1979** [comment]
title starts as an empty string because it's just bad form to create class vars outside of the init IMHO. In my mind all "self"'s should be declared in init.

**Comment by TingPing** [comment]
Alright, should improve the commit message though, title is clearly still a property it just no longer does IO in the getter.

**Comment by JasonLG1979** [comment]
Look at it again, it's not a property it's just a normal instance variable. There is no "getter".

**Comment by JasonLG1979** [comment]
If you like it doesn;t really need to be inside a function it can be naked in init also ```__repr__``` should probably return self.title instead of self.songName like so: 

```python
    def __repr__(self):
        return '<{}.{} {} "{}" by "{}" from "{}">'.format(
            __name__,
            __class__.__name__,
            self.trackToken,
            self.title,
            self.artist,
            self.album,
        )
```

We don't use songName anywhere else in Pithos.

**Comment by TingPing** [comment]
>  it's not a property it's just a normal instance variable. There is no "getter".

At least by my definition an instance variable is a property by default, it just has no custom getter or setter.

Your call on `__repr__`.

**Comment by JasonLG1979** [comment]
What about skipping the function and just putting it in init?

**Comment by TingPing** [comment]
Its ugly eitherway but there is no real benefit to it being a function atm.

**Comment by JasonLG1979** [comment]
There it's all out in the open and I clarified the commit message a bit. I also moved all the instance class vars up above all the ugliness.

**Pull request merged**
