### PR TITLE
style-change-fixup

### PR DESCRIPTION
**Pull request by JasonLG1979**
This should fix an edgecase in which changing to dark variants of themes in gtk inspector doesn't update the ratings icon colors.

### CODE REVIEW

**Comment by TingPing** [comment]
Do come up with a better commit title though =)

**Comment by JasonLG1979** [comment]
Better?

**Comment by JasonLG1979** [comment]
Merge this stuff,lol!!!

**Comment by TingPing** [comment]
Chill man, it hasn't even been one day.

**Pull request merged**
