### PR TITLE
Include genre stations in search

### PR DESCRIPTION
**Pull request by JasonLG1979**
The title pretty much sums it up ;P

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Crap forgot to switch branches... Hold on. I'll fix it.

**Comment by TingPing** [comment]
Good stuff!, I feel like we could improve sorting but I'll leave that for a later change.

**Comment by JasonLG1979** [comment]
> I feel like we could improve sorting but I'll leave that for a later change.

I had to add 'includeNearMatches' to broaden the search results otherwise for example if you entered 80s you wouldn't get any genre results. With includeNearMatches you get some 80's based stations. I'll look into maybe throwing away some of the really low score artist and song results maybe?

**Comment by JasonLG1979** [comment]
For example with "Korn" as a search I ofc get the band Korn but I also get a bunch a other crap with a score lower than 75. I think for artist and song results we could thin out the results a bit by setting 75 as our threshold.

**Comment by JasonLG1979** [comment]
Another prop better idea is to let the user decide what they're searching for Song, Artist or Genre and only show the results they want.

**Comment by TingPing** [comment]
Yea some filter for type would be nice and yes we can probably throw away some really far off results.

**Comment by JasonLG1979** [comment]
Something like:
```python
        l =  [SearchResult('artist', i) for i in results['artists']]
        l += [SearchResult('song',   i) for i in results['songs'] if i['score'] >= 80]
        l += [SearchResult('genre', i) for i in results['genreStations'] if i['score'] >= 80]
        l.sort(key=lambda i: i.score, reverse=True)
```

Will get rid of a lot of the noise.

**Comment by JasonLG1979** [comment]
I can do a quick PR for that bit if you'd like?

**Comment by JasonLG1979** [comment]
Do you want separate filter buttons or just one button that cycles though the filters , all, artist, song, genre?

**Comment by TingPing** [comment]
Probably a drop down radio menu.

**Pull request merged**
