### PR TITLE
Add codec to song text

### PR DESCRIPTION
**Pull request by JasonLG1979**
And tweak the song text style a little bit.

### CODE REVIEW

**Comment by TingPing** [comment]
I always thought showing the bitrate was overly verbose, showing the codec even more so.

**Comment by JasonLG1979** [comment]
I'm kinda an audio nerd I guess. I like to see the codec.

**Comment by JasonLG1979** [comment]
To me it's more complete information.

**Comment by JasonLG1979** [comment]
With:
with

Without:
without

**Comment by JasonLG1979** [comment]
Totally up to you though. Not a huge deal. It's not an absolute must have, but I like it.

**Comment by JasonLG1979** [comment]
I'm going to close this. Hopefully we move to something resembling my latest mockup soon and this will be unneeded.

**Pull request closed without merging**
