### PR TITLE
Get and set Explicit Content Filter State.

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by TingPing** [comment]
The Pandora module is very inconsistent about it but you should probably make this into a property, at the very least combine the two setter functions.

**Comment by JasonLG1979** [comment]
By inconsistent do you mean it this errors if it's called before the user is logged in? If so then yep it can't be called before the user is logged in like during the initial loading of preferences. I could throw a try in the check function so that it will silently fail and return None True or False. That way a toggle/check box in the prefs initially be set to inactive/unclick able and then if/when it returned True or False it could be set to the appropriate setting and become click able?

**Comment by JasonLG1979** [comment]
*throws errors

**Comment by TingPing** [comment]
> By inconsistent do you mean it this errors if it's called before the user is logged in?

No I mean't coding style in terms of using Python properties, I didn't even test this yet.

**Comment by JasonLG1979** [comment]
I'll have to do some reading up on the property decorator. I pretty much know nothing about it.

**Pull request closed without merging**
