### PR TITLE
Sticky buffer fix

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Sorry for the little bit of noise in there. :)

**Comment by TingPing** [comment]
rebase them.

**Comment by TingPing** [comment]
`git pull --rebase upstream master` where upstream is a remote pointing to this repo.

**Comment by TingPing** [comment]
Or ignore that and spam more issues =\

**Comment by JasonLG1979** [comment]
> git push -f origin sticky-buffer-fix

just led to error messages.

**Comment by JasonLG1979** [comment]
'''jason@jason-Inspiron-One-2020:~/pithos$ git push -f origin sticky-buffer-fix
error: src refspec sticky-buffer-fix does not match any.
error: failed to push some refs to 'https://github.com/JasonLG1979/pithos.git''''

**Pull request closed without merging**
