### PR TITLE
Possible fix to the lockup/Random Pause bugs

### PR DESCRIPTION
**Pull request by JasonLG1979**
Start pipeline in PAUSED state. Ignore the buffer messages until the async_done message. Set the buffer-duration property to 15 seconds.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Never mind. Didn't see the pull request before mine. There seems to be a lot of activity lately. I'll wait for the dust to settle a bit to see if anything I've came up with is still relevant/useful.

**Comment by gregsheremeta** [comment]
I just started reviewing @glennimoss 's pull request, but I assume nothing in that changes behavior of the player. It's just a refactor. So your code here should still be relevant.

I ran your experimental branch for the last week, and didn't have one random pause or buffering failure. Which is fantastic :) Let me run this for a few days and we'll see if this is the essence of the fix. If it is, I think we'll merge this first, and let @glennimoss rebase.

**Comment by JasonLG1979** [comment]
His branch won't run for me I get about a zillion import errors...

**Comment by JasonLG1979** [comment]
This is really only a part the way there. I'd like to basically merge all the improvements/changes I made but just as soon as I work the changes into the rebase the base changes again,lol!!!

**Comment by JasonLG1979** [comment]
There's whole kit and caboodle minus @TingPing 's buffer progressbar (which I like very much and would like to include) TingPing's probability going to yell at me for such a huge pull request but hey I get the feeling he must like yelling at me as much as he does it,lol!!! ;P

**Comment by winny-** [comment]
Hi, I think you'd do well to rebase your commits.

**Comment by TingPing** [comment]
>Let me run this for a few days and we'll see if this is the essence of the fix. If it is, I think we'll merge this first, and let @glennimoss rebase.

I think it makes more sense to do it the other way. #175 separates the player logic from the UI which makes it a much better base to fix issues in the player logic.

**Comment by JasonLG1979** [comment]
Well I guess who's ever pull request gets merged 1st the other will have to rebase?

**Comment by JasonLG1979** [comment]
I tried running @glennimoss 's fork but all I get is a bunch of import errors.

**Comment by glennimoss** [comment]
@JasonLG1979 could you comment in my pull request with some info on the import errors your seeing? Thanks.

**Comment by gregsheremeta** [comment]
> Well I guess who's ever pull request gets merged 1st the other will have to rebase?

Generally, yes. But @TingPing makes a valid point:
>  #175 separates the player logic from the UI which makes it a much better base to fix issues in the player logic

Go ahead and redo that first commit and make the new pull request. Let's test it out. Don't add any new commits in that pr. And then maybe @glennimoss can be nice and incorporate your work in #175.

And then if something happens where #175 doesn't work or gets delayed, we can merge your pr.

Make sense?

**Comment by TingPing** [comment]
> When I posted comments on the first commit, the thing to do is to amend your commit, make a new branch, and resubmit the pull request.

Actually Github is smart enough to handle a rebase and force push (if the PR is still open).

>Also, let's make new branches for each "topic". Because when you do a new commit on a branch that has a pull request pending, it adds noise to the pr.

But that is always a good idea..

**Comment by JasonLG1979** [comment]
#175 does A LOT more than just separate the ui code from the player code.(which I'm totally in favor of) It drastically changes the player logic.(making it MUCH more complex) our pull requests are basically forks in the road in regard to the player logic. They are so different that neither applies to each other. If you really wanted to see which player logic is objectively better than have Glenn submit a request that ONLY seperates the existing logic and we can both go from there.

**Comment by glennimoss** [comment]
There's such a fine line between "too complex" and "makes it actually work." ;) (Somewhere between GStreamer 1.2.3 (ubuntu 14.04) and 1.4.3 (ubuntu 14.10) buffering behavior changed and so under certain circumstances the existing strategy doesn't work.)

I do intend to amend my PR with several things. One will be to separate the preparatory work (util type stuff) from the meat of the Gstreamer changes. Feel free to incorporate whatever into the master, I don't mind rebasing.

**Comment by JasonLG1979** [comment]
I'll see if I can't figure out why your fork won't run and if not I'll post the errors.

**Pull request closed without merging**
