### PR TITLE
Tweaks to gstreamer usage.

### PR DESCRIPTION
**Pull request by glennimoss**
These are changes I made while debugging the buffering deadlock issue.

### CODE REVIEW

**Comment by gregsheremeta** [comment]
Hold off on merging -- I'm getting some errors on Fedora. I'll look into it tonight, unless you beat me to it.


INFO - pithos:do_activate:1138 - Pithos 1.0.1
INFO - pithos:set_player_volume:970 - 0.474
INFO - plugin:enable:35 - Enabling module mediakeys
INFO - mediakeys:bind_dbus:36 - Bound media keys with DBUS
INFO - notify:prepare_notify:71 - Notify supports actions
INFO - plugin:enable:35 - Enabling module notify
INFO - plugin:enable:35 - Enabling module notification_icon
INFO - pandora:connect:210 - Time offset is -0.941265344619751
INFO - pithos:pandora_ready:428 - Pandora connected
INFO - pithos:process_stations:448 - Restoring saved station: id = 1123296344967075441
INFO - pithos:station_changed:648 - Selecting station 1123296344967075441; total = 19
INFO - pandora:get_playlist:287 - pandora: Get Playlist
INFO - pithos:start_song:486 - Starting song: index = 0
INFO - pandora:audioUrl:372 - Using audio quality highQuality: 192 mp3
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 731, in handler
    self.check_if_song_is_ad()
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 741, in check_if_song_is_ad
    dur_stat, dur_int = self.player.query_duration(self.time_format)
AttributeError: 'PithosWindow' object has no attribute 'time_format'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 783, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)
AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 731, in handler
    self.check_if_song_is_ad()
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 741, in check_if_song_is_ad
    dur_stat, dur_int = self.player.query_duration(self.time_format)
AttributeError: 'PithosWindow' object has no attribute 'time_format'
INFO - pithos:art_callback:569 - Downloaded album art for 0
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 731, in handler
    self.check_if_song_is_ad()
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 741, in check_if_song_is_ad
    dur_stat, dur_int = self.player.query_duration(self.time_format)
AttributeError: 'PithosWindow' object has no attribute 'time_format'
INFO - pithos:art_callback:569 - Downloaded album art for 1
INFO - pithos:art_callback:569 - Downloaded album art for 2
INFO - pithos:art_callback:569 - Downloaded album art for 3

**Comment by glennimoss** [comment]
Ok, that should fix up my mistakes.

**Comment by gregsheremeta** [comment]
One more:

AttributeError: 'PithosWindow' object has no attribute 'buffer_percent'
Traceback (most recent call last):
  File "/home/greg/projects/pithos-glenn/pithos/pithos.py", line 777, in on_gst_buffering
    logging.debug("Buffering (%i%%)"%self.buffer_percent)

**Comment by glennimoss** [comment]
dur hur

**Comment by gregsheremeta** [comment]
Clean now, thanks :)

**Comment by gregsheremeta** [comment]
Some informal testing feedback. I've been running this for the last few days, and haven't hit the deadlock once. And I haven't patched gstreamer at all.

Thoughts on what's making it work better? Perhaps hooking into async_done ?

**Comment by glennimoss** [comment]
It's possible... I found that I still get deadlocks running this code without the gstreamer fixes. What version of gstreamer are you using?

**Comment by gregsheremeta** [comment]
I'm on 
gstreamer1-1.2.4-1.fc20.x86_64

**Comment by glennimoss** [comment]
And you were getting lockups with the previous pithos code?

**Comment by gregsheremeta** [comment]
All the time :)

**Comment by gregsheremeta** [comment]
By "lockups" I refer to https://github.com/pithos/pithos/issues/94

**Comment by glennimoss** [comment]
Ok, so looking at the 1.2.4 code, the whole section causing the deadlocks I fixed doesn't even exist. So your issue is caused by something else. Hopefully this code did address that successfully. Signs point to yes.

**Comment by gregsheremeta** [comment]
I ran this for a week. Stable, good to merge. Thanks!

**Pull request merged**
