### PR TITLE
fix: delete temp files on exit 

### PR DESCRIPTION
**Pull request by jarebear6expepjozn6rakjq5iczi3irqwphcvb**
I added the `ignore_cleanup_errors=True` flag to make sure the `tempfile` library stayed honest and actually deleted the directories it created.  This prevents the buildup of directories and files and closes issue #686.

If you want to actually use this as a cache I would remove the `tempfile` library and opt for a simpler system for file governance.  You explicitly set `tempdir_base` without it anyway, and there seems to be no other reliance on it elsewhere.

Is actual caching a feature you/others want? Any other meta-data that should be cached?

### CODE REVIEW

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
Sorry, not Gtk gripes but rather because the `tempfile.NamedTemporaryFile(prefix='art-', suffix='.jpeg', dir=tmpdir.name, delete=False) ` object has a false delete flag cause the errors preventing the cleanup.   Not sure if you had a reason set that flag, but either way this PR fixes it.

**Comment by TingPing** [comment]
Could you update the commit message to make sense.

I think re-using the downloaded files would be good but that can be a later change.

**Comment by TingPing** [comment]
You never actually updated the commit message...

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
How is that?

**Comment by TingPing** [comment]
The issue title is not the commit message. `git commit -am 'This is the new message'` will do it. then `git push -f`

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
Got it I think. Thank you

**Pull request merged**
