### PR TITLE
Fix https://github.com/pithos/pithos/issues/329

### LINKED ISSUE #329: Missing titlebar icon in Kubuntu/KDE(and possibly other DE's?)
kde

### PR DESCRIPTION
**Pull request by JasonLG1979**
Fix icon name for main window

Fixes #329

### CODE REVIEW

**Comment by TingPing** [comment]
Please use a useful commit message...:

```
Fix icon name for main window

Fixes #329
```

**Comment by JasonLG1979** [comment]
ok

**Comment by JasonLG1979** [comment]
Does that work?

**Comment by TingPing** [comment]
(You never pushed a new commit, so I just changed the message)

**Pull request closed without merging**
