### PR TITLE
Update to copyright year

### PR DESCRIPTION
**Pull request by RyanNerd**
Small change in about dialog that updates the copyright year.

### CODE REVIEW

**Comment by TingPing** [comment]
Only the start date of a copyright claim matters, beyond that it lasts the year of the author + whatever in the US so there is no point in mentioning it.

**Comment by JasonLG1979** [comment]
Every time Mickey Mouse comes up to go into the public domain they extend the copyright term(no joke, true story). It's like life of the author + 75 years now I think.

**Comment by RyanNerd** [comment]
So should the year even be mentioned then? Currently, it is set in the app as 2012. Here's some more [Disney copyright insanity](https://www.techdirt.com/articles/20170525/10481837456/piracy-killing-hollywood-so-bad-that-disney-made-more-money-2016-than-any-studio-ever.shtml) that is also true.

**Comment by JasonLG1979** [comment]
> So should the year even be mentioned then? Currently, it is set in the app as 2012.

I think you may still have to declare a starting year? If anything it's convention.

**Pull request closed without merging**
