### PR TITLE
Add Help to the main menu

### PR DESCRIPTION
**Pull request by JasonLG1979**
Adds Help to the main menu that opens the wiki in a browser.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
> Add f1 keybinding
> In the appdata file add <kudo>UserDocs</kudo> in <kudos> section.

I got the appdata part but how do you Add f1 keybinding?

**Comment by TingPing** [comment]
See the Quit entry in the menu file.

**Comment by JasonLG1979** [comment]
```&lt;Primary&gt;q```

I get that to quit you do Primary + q but you want help to be just f1 right? Not Primary + f1?

**Comment by JasonLG1979** [comment]
I don't know the syntax.

**Comment by JasonLG1979** [comment]
OK so a little googling tells me that  ```&lt;Primary&gt;q``` basically means ```<Primary>q```... So would ```&lt;f1&gt;``` be correct?

**Comment by TingPing** [comment]
No, just `f1`.

**Comment by JasonLG1979** [comment]
So to be clear: ```<attribute name="accel">f1</attribute>```

**Comment by JasonLG1979** [comment]
Neither ```<attribute name="accel">f1</attribute>``` nor ```<attribute name="accel">&lt;f1&gt;</attribute>``` will work:
```Gtk-WARNING **: Unable to parse accelerator```

**Comment by TingPing** [comment]
Ah my bad it is a capital `F1`

**Comment by JasonLG1979** [comment]
Might want to add that Primary. On my keyboard that lacks fancy media keys I have F1 bound to opening the default media player.

**Comment by TingPing** [comment]
`F1` is the 'standard' for gnome apps and `<Primary>F1` is already used for keyboard shortcuts.

**Comment by JasonLG1979** [comment]
> F1 is the 'standard' for gnome apps and <Primary>F1 is already used for keyboard shortcuts.

Good enough.

**Comment by JasonLG1979** [comment]
All done I think?

**Comment by JasonLG1979** [comment]
Just a thought but you might want to lock the wiki down if it's going t used as a help section.

**Pull request merged**
