### PR TITLE
Fix pause during buffering

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by TingPing** [comment]
Like I've mentioned before I hate the idea of multiple variables representing play and pause, it makes no sense.

**Comment by JasonLG1979** [comment]
I don't like it either but since you made playing a 3 way switch you can't rely on "if self.playing:" for the playpause button.

**Comment by TingPing** [comment]
If we need more than 3 states just factor this into an enum, like:

```python
from enum import Enum
class PlayState(Enum):
    waiting=0
    paused=1
    user_paused=2
    playing=3
```

**Comment by JasonLG1979** [comment]
Cool.

**Comment by JasonLG1979** [comment]
Will that allow for overlapping states. Because it's possible to be waiting for a song to start and be paused at the same time or not be paused and waiting for a song to start or not be waiting for a song to start and be paused or not waiting for a song to start and not be paused. We had something like this when we has song_started to represent only if the song had started or not and playing to represent if it was paused or not.

**Comment by TingPing** [comment]
>  Because it's possible to be waiting for a song to start and be paused at the same time

No its not, that is what #213 was all about. Currently 'waiting' always means waiting to play, if that is changed to pause it just never starts, and if its set to play well just play. There is no need for overlap afaict.

**Comment by JasonLG1979** [comment]
Yes it is. If I hit pause during buffering I'm paused while waiting for a song to start

**Comment by JasonLG1979** [comment]
The old song_started basically meant done initially buffering

**Comment by JasonLG1979** [comment]
The current code in doesn't work because it conflates 2 unrelated things. If we're done initially buffering and if we are currently playing.

**Comment by JasonLG1979** [comment]
@TingPing, I changed it so that self.playing represents playing or paused and self.initially_buffered represents(you guessed it) if the song has been initially buffered with those 2 variable it's possible to represent the 4 possible states of:
1. Being in a Play state(or at least wanting to be) while buffering.
2. Being in a Paused state(or again at least wanting to be) while buffering.
3. Being in a Play state while not buffering.
4. Being in a Paused state while not buffering.

**Pull request closed without merging**
