### PR TITLE
Add, remove and move song seed.

### PR DESCRIPTION
**Pull request by JasonLG1979**
Enables us to add, remove and move song seeds to and from stations as mentioned in #288.

### CODE REVIEW

**Comment by TingPing** [comment]
Looks good but I'd like to wait for when the UI is hooked up to it.

**Comment by JasonLG1979** [comment]
> Looks good but I'd like to wait for when the UI is hooked up to it.

You're the UI guy. I figured you could take this and work your magic,lol!!!

**Comment by TingPing** [comment]
Not likely sorry.

**Comment by JasonLG1979** [comment]
> Not likely sorry.

Well that's a bummer because I don't really know the 1st thing about glade :(

**Comment by JasonLG1979** [comment]
It would be a really killer feature. We're getting very close to feature parity with the webui...

**Comment by JasonLG1979** [comment]
Well could you merge this now so that I(if/when I eventually learn Glade) or someone else can do the UI bits later?

**Comment by TingPing** [comment]
No reason to add dead code just in case.

**Comment by JasonLG1979** [comment]
Ok well I'm working on adding "remove this song from this station" and "create station based on this song" to the right click menu. I'm still not sure how to do the whole moving thing.

**Comment by JasonLG1979** [comment]
I'm going to close this. It may be revisited at a later date when the UI bits are also in place.

**Pull request closed without merging**
