### PR TITLE
More complete PULSE_PROPs

### PR DESCRIPTION
**Pull request by JasonLG1979**
Useful for applications that interact with PulseAudio like https://github.com/masmu/pulseaudio-dlna

### CODE REVIEW

**Comment by TingPing** [comment]
Are these properties documented anywhere?

**Comment by JasonLG1979** [comment]
http://0pointer.de/lennart/projects/pulseaudio/doxygen/proplist_8h.html

**Comment by JasonLG1979** [comment]
> Please include that link in the commit message.

OK

> Also 'AudioStream' seems a bit vague?

I know I didn't know what to put there. That's what Firefox uses for the name?

**Comment by JasonLG1979** [comment]
I can do something like 'Pandora Radio Stream' ?

**Comment by TingPing** [comment]
Based upon the docs it seems that `Artist - Song` or such would be acceptable.

**Comment by JasonLG1979** [comment]
So skip name then?

**Comment by TingPing** [comment]
Hmm? I'm saying `name` is basically just a user friendly name of the current song.

**Comment by JasonLG1979** [comment]
Artist and song are already covered with artist and title

**Comment by JasonLG1979** [comment]
Name would be the name of the stream. Something in my mind would not change. A general description of the stream.

**Comment by TingPing** [comment]
The example given is `e.g. "Guns'N'Roses: Civil War"`. I read that as a user readable name of the song.

**Comment by JasonLG1979** [comment]
Didn't see that ok.

**Comment by JasonLG1979** [comment]
I'll match the example then.

**Comment by JasonLG1979** [comment]
Done

**Pull request merged**
