### PR TITLE
Mpris playlist support

### PR DESCRIPTION
**Pull request by JasonLG1979**
The name says it all. @TingPing waiting on this to move forward with tight Pithos integration in https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
My plan is to basically make the Notification Tray Icon obsolete for GNOME Shell by adding Pithos specific tweaks into the extension for example little things like changing the Playlist title to Station and bigger things like replacing ratings in the extension with support for Love/Tired/Ban. (ofc the tweaks would not effect other apps)

**Comment by JasonLG1979** [comment]
I just pushed a commit to https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer that fixes a lot of bugs, redesigned the UI, adds a few new features and that added the ability for players to be added to a couple lists that effects the UI. For Pithos that means no stop button since we don't use it and the playlists menu is renamed to "Stations", since that's what we would use the playlist interface for. I would love to move forward with a Pithos specific interface forlove/tired/ban so I can replace the rating stars with love/tired/ban buttons.

screenshot from 2017-01-29 21-18-58
screenshot from 2017-01-29 21-19-01

**Comment by JasonLG1979** [comment]
Oh and another neat little feature is since the extension listens for the Orderings prop and I've connected that prop to the stations sort order setting the stations/playlists in the extension match and change to the sort order in the stations popover.

**Comment by JasonLG1979** [comment]
As a side note. With this Pithos will be the only player that I know of to have a fully functional playlist interface. Not even Rhythmbox get's it 100% right. https://bugzilla.gnome.org/show_bug.cgi?id=775207

**Comment by JasonLG1979** [comment]
@TingPing do you want me to squash this into 1 commit?

**Comment by TingPing** [comment]
Sure

**Comment by JasonLG1979** [comment]
OK I'll make a fairly detailed commit message.

**Pull request merged**
