### PR TITLE
Refactor audio player code. 

### PR DESCRIPTION
**Pull request by glennimoss**

### CODE REVIEW

**Comment by TingPing** [comment]
Fix all the random whitespace changes.

**Comment by TingPing** [comment]
New files need license header.

**Comment by JasonLG1979** [comment]
@glennimoss This is what I get when I try to run your fork.
```
Traceback (most recent call last):
  File "/usr/local/bin/pithos", line 9, in <module>
    load_entry_point('pithos==1.0.1', 'gui_scripts', 'pithos')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.0.1-py3.4.egg/pithos/pithos.py", line 33, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/local/lib/python3.4/dist-packages/pithos-1.0.1-py3.4.egg/pithos/PreferencesPithosDialog.py", line 24, in <module>
    from .pandora.data import *
ImportError: No module named 'pithos.pandora'
```

**Comment by glennimoss** [comment]
@JasonLG1979 Do you have anything weird going on with PYTHONPATH or something?

**Comment by JasonLG1979** [comment]
No not as far as I know. Running on stock Ubuntu 15.04 with the exception of the handbrake ppa, webupd8 java ppa, Minecraft installer ppa, and Google Chrome repo. Standard install method. Clone your fork, cd to the source folder, run the setup.

**Comment by JasonLG1979** [comment]
The stock source runs just fine.

**Comment by JasonLG1979** [comment]
The problem seems to be that the Pandora folder is not copied/installed to /usr/local/lib/python3.4/dist-packages/pithos-1.0.1-py3.4.egg/pithos/

**Comment by glennimoss** [comment]
How are you installing it? For me `sudo python3 setup.py install` does put the pithos/panodra folder there.

What's your version of setuptools? As in:
```python
import setuptools
setuptools.__version__
```

**Comment by JasonLG1979** [comment]
Yep, ```sudo python3 setup.py install```
```
import setuptools
print(setuptools.__version__)
```
Says 12.2

**Comment by JasonLG1979** [comment]
@TingPing does it run on Fedora?

**Comment by TingPing** [comment]
I only ran `./debug.py -v` and it did mostly work for me. (I'm not on f21 anymore though)

**Comment by JasonLG1979** [comment]
Are there files that I should manually delete that setup isn't catching when migrating from stock to your fork maybe?

**Comment by TingPing** [comment]
Its generally a good idea to remove any old install. His new code also makes use of importing pithos directly which sort of breaks ./debug.py since it relies relative imports only.

**Comment by JasonLG1979** [comment]
OK when I get home from work I'll search my filesystem for Pithos related files. It might not be a bad idea to include that in the setup.py.

**Comment by JasonLG1979** [comment]
Same error messages as above when trying to run it on a Ubuntu 15.04 LiveUSB. ./debug.py works though. And if I change sys.argv.append('-tv') to sys.argv.append('-vv') It logins into Pandora and says it buffers to over 2400% at times(it actually says over 1000% on a regular basis) Some times the song plays sometimes not. Not very usable.

**Comment by glennimoss** [comment]
@JasonLG1979 I tried it with setuptools version 12.2 (I removed the existing pithos installation first) and all files were installed as I would expect...

**Comment by JasonLG1979** [comment]
On 15.04?

**Comment by glennimoss** [comment]
No, 14.10. Let me spin up a 15.04 vm and see what's what.

**Comment by JasonLG1979** [comment]
Probably a bug in setuptools or Ubuntu 15.04. Weird thing is the stock source works just fine.

**Comment by JasonLG1979** [comment]
My branch also installs and works perfectly(even without your gstreamer patch) on Ubuntu 14.10 and 15.04. No random pauses at the beginning of songs and no deadlocks.

https://github.com/JasonLG1979/pithos/tree/JasonLG1979-Possible-fix-to-the-lockup-bug

Test it out.

**Comment by glennimoss** [comment]
Ok I'm going to back WAY up. I will branch from @JasonLG1979's fix branch and only separate the player logic from the gui logic. Any functionality changes can come after that.

I think we need a better communication medium than comments on pull requests. I made a chat room at https://gitter.im/pithos/pithos to start. Let's try that for a bit.

**Comment by TingPing** [comment]
> I will branch from @JasonLG1979's fix branch and only separate the player logic from the gui logic.

Well thats still multiple steps at a time. Separate first, then improve imo.

>I think we need a better communication medium than comments on pull requests. 

As I said in the other issue there is already #pithos on freenode.

**Pull request closed without merging**
