### PR TITLE
Get bitrate and codec form Pandora

### PR DESCRIPTION
**Pull request by JasonLG1979**
And nix the tag handler.

Should be all good this time. Thanks for being so patient.

### CODE REVIEW

**Comment by TingPing** [comment]
Please stop using the stupid github webui so you don't make one commit per file..

**Comment by JasonLG1979** [comment]
Ok, I'll do my best in the future to squash my commits before sending PR's. Still trying to figure it out.

**Comment by TingPing** [comment]
The basics with git are not terrible (though it can get complex fast). Your  workflow should be something like this:

```sh
git checkout -b some_feature
# Edit files locally
git add file1.py file2.py
git commit
git push origin some_feature
# Then open github to make the PR
```

If you ever edit a single file in the webui you are doing something wrong :P

**Comment by JasonLG1979** [comment]
> If you ever edit a single file in the webui you are doing something wrong :P

I'm wrong a lot then,lol!!!

**Comment by JasonLG1979** [comment]
I stared a branch that I can mutilate for the sake of learning git.

**Comment by TingPing** [comment]
If you ever need help with git IRC is the place to be. #git and #github are full of helpful people. (and ofc me in #pithos)

**Comment by JasonLG1979** [comment]
Will do thanks.

Other than my git ineptitude is this more of alone the lines of what you were looking for. It actually removed more code than it added, which is a good thing right? The less code the better?

**Comment by TingPing** [comment]
Looks good at a glance.

**Comment by gregsheremeta** [comment]
Code looks good to me. Should all be in one commit, though. Ping me on IRC if you need help with that.

**Comment by JasonLG1979** [comment]
@gregsheremeta and/or @TingPing - This has been sitting for a while should I just close it?

**Pull request closed without merging**
