### PR TITLE
Logging prefs fix up

### PR DESCRIPTION
**Pull request by JasonLG1979**
Make it so you can actually read the title of the prefs window... Oops... sorry about that :(

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Thanks. Sorry about that again.... Anyway, new release time?

**Comment by TingPing** [comment]
I'll sit on it for a bit just in case of any new issues since a lot of changes landed. Also if you want to help making a changelog would be nice =)

**Comment by JasonLG1979** [comment]
Good idea. Freeze everything. Nothing new except new bug fixes related to recent changes. I like it. I'll have to read the last change log to see what's been done since the last release. It's all a blur to me. I haven't ran an actual stable release in a couple years,lol!!!

**Comment by JasonLG1979** [comment]
A quick look and the commits since the last release here's a quick rundown. It's not everything but it's a start. http://pastebin.com/49KCzFxr

**Comment by JasonLG1979** [comment]
I'm not sure how to word a lot of your fixes/changes. A lot of what you do is under the hood. Not really user facing.

**Pull request merged**
